[package]
name = "mrx-generate"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = { version = "0.9.20", features = ["derive"] }
mrx-utils = { path = "../mrx-utils" }
tempfile = "3.23.0"
thiserror = "2.0.17"
