[package]
name = "mrx-build"
version = "0.1.0"
edition = "2024"

[dependencies]
mrx-cli = { path = "../mrx-cli" }
mrx-utils = { path = "../mrx-utils" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"
thiserror = "2.0.17"
